namespace WizardsVsWirebacks.GameObjects;

public enum BuildingType
{
    Chainsawmancer,
    Lawyer,
    Archivist,
    Oracle,
    Leadconjurer,
    Transmuter,
    Artificer,
    WraithShaman,
    Chronomancer,
    Thaumaturge,
    Biomancer,
    Soothsayer,
    Underwearwarper,
    BloodBard,
    Runesmith,
    Psion,
    Monk,
    Soulslinger,
    Occultist,
    Kurdaitcha,
    Illusionist,
    Syncretist,
    Garaboncid,
    Totemist,
    Archon,
}